### ISSUE TITLE
--show option error

### ISSUE THREAD

**Issue by otets-u** [OpenDriveLab/LaneSegNet#20]
Hello, 

Thank you for great work.
I'm really interested in this project.

Firstly, I could run the estimation with learned coefficients on my 2 GPUs (RTX3070) environment and get the below result.

```bash
(lanesegnet) root@my-pc:/opt/LaneSegNet# ./tools/dist_test.sh 2

# omitting log ...

load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4806/4806, 8.6 task/s, elapsed: 556s, ETA:     0s2024-02-21 14:04:12,028 - mmdet - INFO - Starting format results...
2024-02-21 14:08:19,540 - mmdet - INFO - Starting openlanev2 evaluate...
calculating distances:: 100%|███████████████| 4806/4806 [09:46<00:00,  8.20it/s]
{'mAP': 0.3345044255256653, 'AP_ls': 0.31961587, 'AP_ped': 0.349393, 'TOP_lsls': 0.2537521315543861}
```

And then I tried to run the estimation with --show option.
As a result below error occured.

Could you give me any tips to solve this error??

sincerely.

```bash
(lanesegnet) root@my-pc:/opt/LaneSegNet# ./tools/dist_test.sh 2 --show
++ date +%y%m%d.%H%M%S
+ timestamp=240221.151626
+ WORK_DIR=work_dirs/lanesegnet
+ CONFIG=projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py
+ CHECKPOINT=work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
+ GPUS=2
+ PORT=28510
+ python -m torch.distributed.run --nproc_per_node=2 --master_port=28510 tools/test.py projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth --launcher pytorch --out-dir work_dirs/lanesegnet/test --eval openlane_v2 --show
+ tee work_dirs/lanesegnet/test.240221.151626.log
WARNING:__main__:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4806/4806, 8.6 task/s, elapsed: 559s, ETA:     0sERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 1 (pid: 2738) of binary: /opt/miniconda3/envs/lanesegnet/bin/python
/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 2738 (local_rank 1) FAILED (exitcode -11)
Error msg: Signal 11 (SIGSEGV) received by PID 2738
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/run.py", line 702, in <module>
    main()
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/run.py", line 698, in main
    run(args)
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
*************************************************
               tools/test.py FAILED              
=================================================
Root Cause:
[0]:
  time: 2024-02-21_15:26:02
  rank: 1 (local_rank: 1)
  exitcode: -11 (pid: 2738)
  error_file: <N/A>
  msg: "Signal 11 (SIGSEGV) received by PID 2738"
=================================================
Other Failures:
  <NO_OTHER_FAILURES>
*************************************************

/opt/miniconda3/envs/lanesegnet/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 32 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```

```bash
(lanesegnet) root@my-pc:/opt/LaneSegNet# ./tools/dist_test.sh 2 --show
++ date +%y%m%d.%H%M%S
+ timestamp=240221.154229
+ WORK_DIR=work_dirs/lanesegnet
+ CONFIG=projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py
+ CHECKPOINT=work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
+ GPUS=2
+ PORT=28510
+ python -m torch.distributed.run --nproc_per_node=2 --master_port=28510 tools/test.py projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth --launcher pytorch --out-dir work_dirs/lanesegnet/test --eval openlane_v2 --show
+ tee work_dirs/lanesegnet/test.240221.154229.log
WARNING:__main__:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4806/4806, 8.6 task/s, elapsed: 556s, ETA:     0s
[E ProcessGroupNCCL.cpp:566] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806124 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:325] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1806124 milliseconds before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 1408) of binary: /opt/miniconda3/envs/lanesegnet/bin/python
/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 1408 (local_rank 0) FAILED (exitcode -6)
Error msg: Signal 6 (SIGABRT) received by PID 1408
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/run.py", line 702, in <module>
    main()
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/run.py", line 698, in main
    run(args)
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/miniconda3/envs/lanesegnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
************************************************
              tools/test.py FAILED              
================================================
Root Cause:
[0]:
  time: 2024-02-21_16:22:06
  rank: 0 (local_rank: 0)
  exitcode: -6 (pid: 1408)
  error_file: <N/A>
  msg: "Signal 6 (SIGABRT) received by PID 1408"
================================================
Other Failures:
  <NO_OTHER_FAILURES>
************************************************

```

**Comment by sephyli** [comment]
The main error of your log is Signal 11 (SIGSEGV). It's maybe an internal bug in torch/mmcv ddp. I don't encouter this issue in difference machines yet. But you can try to install another version of mm-series package and torch.

```
torch==2.0
torchvision==0.15.0
mmcls==0.25.0
mmcv-full==1.6.0
mmdet==2.26.0
mmdet3d==1.0.0rc6
mmsegmentation==0.29.1
with CUDA 11.7/11.8
```

**Comment by otets-u** [comment]
Hello, @sephyli 
Thank you for reply.

I could run the LaneSegNet with ```--show``` option after prepairing your telling environment by Docker.
As a result, I got the below output in colsole and visuallized image.

Would it be OK about the LaneSegNet behavior??

```
(lanesegnet) root@my-pc:/opt/LaneSegNet# ./tools/dist_test.sh 2 --show
++ date +%y%m%d.%H%M%S
+ timestamp=240228.014608
+ WORK_DIR=work_dirs/lanesegnet
+ CONFIG=projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py
+ CHECKPOINT=work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
+ GPUS=2
+ PORT=28510
+ python -m torch.distributed.run --nproc_per_node=2 --master_port=28510 tools/test.py projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth --launcher pytorch --out-dir work_dirs/lanesegnet/test --eval openlane_v2 --show
+ tee work_dirs/lanesegnet/test.240228.014608.log
WARNING:__main__:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
load checkpoint from local path: work_dirs/lanesegnet/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4806/4806, 8.6 task/s, elapsed: 560s, ETA:     0s2024-02-28 01:55:49,196 - mmdet - INFO - Visualizing results at work_dirs/lanesegnet/test/vis/...
No protocol specified
2024-02-28 01:55:57,188 - mmdet - INFO - Visualize done.
2024-02-28 01:55:57,188 - mmdet - INFO - Starting format results...
2024-02-28 02:00:03,855 - mmdet - INFO - Starting openlanev2 evaluate...
calculating distances:: 100%|███████████████| 4806/4806 [09:37<00:00,  8.32it/s]
{'mAP': 0.3345044255256653, 'AP_ls': 0.31961587, 'AP_ped': 0.349393, 'TOP_lsls': 0.2537521315543861}
```

![Screenshot from 2024-02-28 14-56-29](https://github.com/OpenDriveLab/LaneSegNet/assets/43978737/8904ba21-6129-4a32-9749-a9ce6a9f52d6)
