### ISSUE TITLE
dist_test.sh error

### ISSUE THREAD

**Issue by luckynote** [OpenDriveLab/LaneSegNet#23]
./tools/dist_test.sh 1 
++ date +%y%m%d.%H%M%S
+ timestamp=240322.110416
+ WORK_DIR=model
+ CONFIG=projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py
+ CHECKPOINT=model/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
+ GPUS=1
+ PORT=28510
+ python3.8 -m torch.distributed.run --nproc_per_node=1 --master_port=28510 tools/test.py projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py model/lanesegnet_r50_8x1_24e_olv2_subset_A.pth --launcher pytorch --out-dir model/test --eval openlane_v2
+ tee model/test.240322.110416.log
^C
root@10-0-5-174:/jfs/liutao/work_docker/LaneSegNet# ./tools/dist_test.sh 1 
++ date +%y%m%d.%H%M%S
+ timestamp=240322.110820
+ WORK_DIR=model
+ CONFIG=projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py
+ CHECKPOINT=model/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
+ GPUS=1
+ PORT=28510
+ python3.8 -m torch.distributed.run --nproc_per_node=1 --master_port=28510 tools/test.py projects/configs/lanesegnet_r50_8x1_24e_olv2_subset_A.py model/lanesegnet_r50_8x1_24e_olv2_subset_A.pth --launcher pytorch --out-dir model/test --eval openlane_v2
+ tee model/test.240322.110820.log
load checkpoint from local path: model/lanesegnet_r50_8x1_24e_olv2_subset_A.pth
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/test.py", line 263, in <module>
    main()
  File "tools/test.py", line 233, in main
    outputs = multi_gpu_test(model, data_loader, 
  File "/usr/local/lib/python3.8/dist-packages/mmdet/apis/test.py", line 107, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/usr/local/lib/python3.8/dist-packages/mmdet/datasets/samplers/distributed_sampler.py", line 47, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 32766) is killed by signal: Terminated. 
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 32531) of binary: /usr/bin/python3.8
/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 32531 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 702, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 698, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
          tools/test.py FAILED         
=======================================
Root Cause:
[0]:
  time: 2024-03-22_11:08:41
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 32531)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

**Comment by luckynote** [comment]
lanesegnet_r50_8x1_24e_olv2_subset_A.py
![image](https://github.com/OpenDriveLab/LaneSegNet/assets/18484155/64d641f5-71d0-437d-97cb-39eae12401ec)
修改test 数据集为data_dict_subset_A_test_lanesegnet.pkl后，可以正常执行测试程序，不确定val是否生成有问题
![image](https://github.com/OpenDriveLab/LaneSegNet/assets/18484155/b88d4563-3ff1-4128-8c3b-7f19673453e8)

**Comment by luckynote** [comment]
是数据预处理生成的.pkl问题，该问题已经解决

**Comment by AvinsWang** [comment]
I got the same issue, but didn't work with following your method. here is what I did at last [Issue #17](https://github.com/OpenDriveLab/LaneSegNet/issues/17)
