### ISSUE TITLE
Training issue 

### ISSUE THREAD

**Issue by TmacTmac1992** [OpenDriveLab/LaneSegNet#3]
Hi, when I running the training scripts, I got this issue. 

Traceback (most recent call last):
  File "/home/gpu/anaconda3/envs/lanesegnet/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/gpu/anaconda3/envs/lanesegnet/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects'

**Comment by TmacTmac1992** [comment]
Solved

**Comment by raozhongyu** [comment]
Hi, I meet the same question,  how do you solve it?

**Comment by sephyli** [comment]
If your error looks like: `ModuleNotFoundError: No module named 'projects'`:
Please add `export PYTHONPATH="Path/to/LaneSegNet/":$PYTHONPATH` in the `dist_train.sh` shell script or your `.bashrc` file.

**Comment by raozhongyu** [comment]
> If your error looks like: `ModuleNotFoundError: No module named 'projects'`: Please add `export PYTHONPATH="Path/to/LaneSegNet/":$PYTHONPATH` in the `dist_train.sh` shell script or your `.bashrc` file.

Thanks a lot.
